version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kentik-aws-map-builder"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18kkkg7scjuyo"
s3_prefix = "kentik-aws-map-builder"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CloudMapsServiceHost=\"http://localhost:8151\" AuthorizationEmail=\"remi@kentik.com\" AuthorizationApiToken=\"cafebabe\" AuthorizationAccessToken=\"eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiJyZW1pQGtlbnRpay5jb20iLCJ1c2VyX2lkIjo3MjU5LCJjb21wYW55X2lkIjoxMDEzLCJzY29wZXMiOiJhZG1pbi5jbG91ZF9tYXBzIGFkbWluLmNsb3VkX21hcHM6d3JpdGUifQ.CjLJLRT3CG0v-8oPiOjnqNteZunka22Xd4vLulXiMi0\" "
image_repositories = []
