AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Publishers domain

Parameters:
  CloudMapsServiceHost:
    Description: Storage provider host address used to determine where to put output for generated AWS maps
    Type: String
  AuthorizationEmail:
    Type: String
    Description: Email used for Kentik API authorization
  AuthorizationApiToken:
    Type: String
    Description: Service API token used for Kentik API authorization
  PollingPeriod:
    Type: String
    Description: Schedule expression to determine how often to run the network topology collection
    Default: rate(1 hour)
  ExposeWithApi:
    Type: Number
    Description: Flag to control if to expose the network topology collection with API gateway endpoint
    Default: 0

Conditions:
  ExposeWithApiCondition: !Not [!Equals [!Ref ExposeWithApi, 0]]

Globals:
  Function:
    Runtime: nodejs14.x
    Handler: src/index.handler
    MemorySize: 512
    Timeout: 900
    Environment:
      Variables:
        CLOUDMAPS_SERVICE_HOST: !Ref CloudMapsServiceHost
        AUTHORIZATION_EMAIL:  !Ref AuthorizationEmail
        AUTHORIZATION_API_TOKEN: !Ref AuthorizationApiToken

Resources:
  Api:
    Type: AWS::Serverless::Api
    Condition: ExposeWithApiCondition
    Properties:
      StageName: Production
      DefinitionBody:
        swagger: 2.0
        info:
          title: !Sub "Kentik AWS Map Builder API"
        schemes: ["https"]
        paths:
          /map/{action}:
            get:
              x-amazon-apigateway-integration:
                uri: { "Fn::Sub": [ "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${__Lambda__}/invocations", { "__Lambda__": !GetAtt GenerateMapFunction.Arn }]}
                httpMethod: "POST"
                type: "aws_proxy"

  GenerateMapFunctionApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Condition: ExposeWithApiCondition
    Properties:
      Action: lambda:invokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName: !GetAtt GenerateMapFunction.Arn
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/GET/map/{action}"

  GenerateMapFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/generate-map
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref PollingPeriod
      Policies:
        -
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Action:
                - "ec2:Describe*"
                - "ec2:Search*"
                - "ec2:List*"
                - "directconnect:Describe*"
                - "directconnect:List*"
                - "elasticloadbalancing:Describe*"
                - "network-firewall:Describe*"
                - "network-firewall:List*"
              Resource: "*"
